// This .js file is auto-generated by `createCesium()` from VeRoViz
// Display nodes for cesium application

function displayNodes() {
    var pin = new Array;
    pin[0] = viewer.entities.add({
        name : '0',
        parent : nodePins,
        description : 'd11',
        position : Cesium.Cartesian3.fromDegrees(-78.77059936523439, 43.06043086875781),
        billboard : {
            image : pinBuilder.fromText('0', Cesium.Color.RED, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[1] = viewer.entities.add({
        name : '1',
        parent : nodePins,
        description : 'd22',
        position : Cesium.Cartesian3.fromDegrees(-78.69506835937501, 43.05842514826838),
        billboard : {
            image : pinBuilder.fromText('1', Cesium.Color.RED, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[2] = viewer.entities.add({
        name : '2',
        parent : nodePins,
        description : 'c13',
        position : Cesium.Cartesian3.fromDegrees(-78.72940063476564, 43.00424589515733),
        billboard : {
            image : pinBuilder.fromText('2', Cesium.Color.BLUE, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[3] = viewer.entities.add({
        name : '3',
        parent : nodePins,
        description : 'c24',
        position : Cesium.Cartesian3.fromDegrees(-78.78845214843751, 43.02532128785062),
        billboard : {
            image : pinBuilder.fromText('3', Cesium.Color.BLUE, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

}