// This .js file is auto-generated by `createCesium()` from VeRoViz
// Display nodes for cesium application

function displayNodes() {
    var pin = new Array;
    pin[0] = viewer.entities.add({
        name : '0',
        parent : nodePins,
        description : 'd11',
        position : Cesium.Cartesian3.fromDegrees(-78.74862670898439, 43.05692081484412),
        billboard : {
            image : pinBuilder.fromText('0', Cesium.Color.RED, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[1] = viewer.entities.add({
        name : '1',
        parent : nodePins,
        description : 'd22',
        position : Cesium.Cartesian3.fromDegrees(-78.64837646484376, 43.03635789263302),
        billboard : {
            image : pinBuilder.fromText('1', Cesium.Color.RED, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[2] = viewer.entities.add({
        name : '2',
        parent : nodePins,
        description : 'c13',
        position : Cesium.Cartesian3.fromDegrees(-78.72253417968751, 43.02231096029591),
        billboard : {
            image : pinBuilder.fromText('2', Cesium.Color.BLUE, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[3] = viewer.entities.add({
        name : '3',
        parent : nodePins,
        description : 'c24',
        position : Cesium.Cartesian3.fromDegrees(-78.69369506835939, 43.072463813847975),
        billboard : {
            image : pinBuilder.fromText('3', Cesium.Color.BLUE, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

}